[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  command = "npm run build:client"
  publish = "client/build"

[context.production.environment]
  NODE_VERSION = "18"
  CI = "false"

[context.deploy-preview]
  command = "npm run build:client"
  publish = "client/build"
